# Generated by Django 6.1 on 2026-09-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_classroom_level_alter_classroom_capacity_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secondary_subjects',
            field=models.ManyToManyField(blank=True, help_text='Assigned Subjects (For Secondary Teachers)', related_name='subject_teachers', to='academics.subject'),
        ),
    ]
