# Generated by Django 6.1 on 2026-08-06 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('test2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('test3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuality', models.CharField(choices=[('EXCELLENT', 'A - Excellent'), ('VERY_GOOD', 'B - Very Good'), ('GOOD', 'C - Good'), ('SATISFACTORY', 'D - Satisfactory'), ('NEEDS_IMPROVEMENT', 'E - Needs Improvement')], default='GOOD', max_length=25)),
                ('neatness_cleanliness', models.CharField(choices=[('EXCELLENT', 'A - Excellent'), ('VERY_GOOD', 'B - Very Good'), ('GOOD', 'C - Good'), ('SATISFACTORY', 'D - Satisfactory'), ('NEEDS_IMPROVEMENT', 'E - Needs Improvement')], default='GOOD', max_length=25)),
                ('courtesy_respect', models.CharField(choices=[('EXCELLENT', 'A - Excellent'), ('VERY_GOOD', 'B - Very Good'), ('GOOD', 'C - Good'), ('SATISFACTORY', 'D - Satisfactory'), ('NEEDS_IMPROVEMENT', 'E - Needs Improvement')], default='GOOD', max_length=25)),
                ('obedience_discipline', models.CharField(choices=[('EXCELLENT', 'A - Excellent'), ('VERY_GOOD', 'B - Very Good'), ('GOOD', 'C - Good'), ('SATISFACTORY', 'D - Satisfactory'), ('NEEDS_IMPROVEMENT', 'E - Needs Improvement')], default='GOOD', max_length=25)),
                ('relationship_with_others', models.CharField(choices=[('EXCELLENT', 'A - Excellent'), ('VERY_GOOD', 'B - Very Good'), ('GOOD', 'C - Good'), ('SATISFACTORY', 'D - Satisfactory'), ('NEEDS_IMPROVEMENT', 'E - Needs Improvement')], default='GOOD', max_length=25)),
                ('leadership_responsibility', models.CharField(choices=[('EXCELLENT', 'A - Excellent'), ('VERY_GOOD', 'B - Very Good'), ('GOOD', 'C - Good'), ('SATISFACTORY', 'D - Satisfactory'), ('NEEDS_IMPROVEMENT', 'E - Needs Improvement')], default='GOOD', max_length=25)),
                ('class_teacher_remark', models.TextField(blank=True, help_text='General comments from Class Teacher', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicterm')),
            ],
        ),
    ]
