# Generated by Django 6.1 on 2026-08-12 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='behaviorassessment',
            old_name='courtesy_respect',
            new_name='cheerfulness',
        ),
        migrations.RenameField(
            model_name='behaviorassessment',
            old_name='leadership_responsibility',
            new_name='helpfulness',
        ),
        migrations.RenameField(
            model_name='behaviorassessment',
            old_name='neatness_cleanliness',
            new_name='homework',
        ),
        migrations.RenameField(
            model_name='behaviorassessment',
            old_name='obedience_discipline',
            new_name='honesty',
        ),
        migrations.RenameField(
            model_name='behaviorassessment',
            old_name='punctuality',
            new_name='leadership',
        ),
        migrations.RenameField(
            model_name='behaviorassessment',
            old_name='relationship_with_others',
            new_name='neatness',
        ),
        migrations.AddField(
            model_name='academicterm',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='next_term_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behaviorassessment',
            name='head_teacher_remark',
            field=models.TextField(blank=True, help_text='Principal / Head Teacher Remarks', null=True),
        ),
        migrations.AddField(
            model_name='behaviorassessment',
            name='obedience',
            field=models.CharField(choices=[('EXCELLENT', 'A - Excellent'), ('VERY_GOOD', 'B - Very Good'), ('GOOD', 'C - Good'), ('SATISFACTORY', 'D - Satisfactory'), ('NEEDS_IMPROVEMENT', 'E - Needs Improvement')], default='GOOD', max_length=25),
        ),
        migrations.AddField(
            model_name='behaviorassessment',
            name='responsibility',
            field=models.CharField(choices=[('EXCELLENT', 'A - Excellent'), ('VERY_GOOD', 'B - Very Good'), ('GOOD', 'C - Good'), ('SATISFACTORY', 'D - Satisfactory'), ('NEEDS_IMPROVEMENT', 'E - Needs Improvement')], default='GOOD', max_length=25),
        ),
        migrations.AddField(
            model_name='behaviorassessment',
            name='self_control',
            field=models.CharField(choices=[('EXCELLENT', 'A - Excellent'), ('VERY_GOOD', 'B - Very Good'), ('GOOD', 'C - Good'), ('SATISFACTORY', 'D - Satisfactory'), ('NEEDS_IMPROVEMENT', 'E - Needs Improvement')], default='GOOD', max_length=25),
        ),
        migrations.AddField(
            model_name='behaviorassessment',
            name='sports',
            field=models.CharField(choices=[('EXCELLENT', 'A - Excellent'), ('VERY_GOOD', 'B - Very Good'), ('GOOD', 'C - Good'), ('SATISFACTORY', 'D - Satisfactory'), ('NEEDS_IMPROVEMENT', 'E - Needs Improvement')], default='GOOD', max_length=25),
        ),
        migrations.AddField(
            model_name='behaviorassessment',
            name='stewardship',
            field=models.CharField(choices=[('EXCELLENT', 'A - Excellent'), ('VERY_GOOD', 'B - Very Good'), ('GOOD', 'C - Good'), ('SATISFACTORY', 'D - Satisfactory'), ('NEEDS_IMPROVEMENT', 'E - Needs Improvement')], default='GOOD', max_length=25),
        ),
        migrations.AddField(
            model_name='classroom',
            name='section',
            field=models.CharField(choices=[('GRADE_5', 'Grade 5'), ('GRADE_6', 'Grade 6'), ('SECONDARY', 'Secondary')], default='GRADE_5', max_length=20),
        ),
        migrations.AlterField(
            model_name='behaviorassessment',
            name='class_teacher_remark',
            field=models.TextField(blank=True, help_text='Class Teacher Remarks', null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Assigned by Deputy Head', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_classrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubjectTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('teacher', 'classroom', 'subject')},
            },
        ),
    ]
